### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by billiejoenahema** [billiejoenahema/kajisuke#13]
- [x] make policy
- [x] change logging from stack to daily
- [ ] feat calendar
- [x] add invalid feedback style
- [x] user profile
  - [x] zipcode split input
  - [x] birth value selector
- [x] display Characters used: 0 out of <maxLength>.
- [x] feat update archive
- [x] apply invalid feedback to login form
- [x] make generate user command
- [x] install php-ide-helper
